/*

Uses the text file generated by getRMSMean.cpp to plot
the average RMS for each channel across a range of 400
runs.

It does crash at the end, but it saves the plots before
that, so it was good enough for me.

Will Benoit
December 6th 2016

*/

#include "TH1F.h"
#include "TGraph.h"
#include "TFile.h"
#include "TCanvas.h"
#include <fstream>
#include <math.h>
#include <iostream>

using namespace std;

int graphAll(){
 
  //Lengths are the number of means in the text file
  double runs[14004], rms[14004];
  
  ifstream read("RMS Means.txt");
  
  int skips = 0; //Some runs don't have data files. This is to count them.
  
  for(int run = 5200; run < 5602; run++){
    
    //These runs don't have data files. Increments skips to account for that
    if(run == 5275 || run == 5289 || run == 5359 || run == 5493 || run == 5510 || run == 5535 || run == 5578 || run == 5580){
      skips++;
      continue;
    }
  
    //Filling the arrays
    for(int ch = 0; ch < 36; ch++){
      int index = 36*(run-5200-skips) + ch;
      runs[index] = run;
      read >> rms[index];
    }
  }
  
  read.close();
  
  //5602-5200 = 402. 402 minus the 8 missing runs is 394. But I'm pretty sure these need to be length 389, because 14004/36 = 389
  //This might be the reason it crashes. I'm not sure I ever figured out why the numbers were mismatched
  double tempX[389], tempY[389];
  
  //Filling the temp arrays with all the values for each channel
  for(int graph = 0; graph < 36; graph++){
    
    for(int i = graph; i < 14004; i+=36){
      int index = floor(i/36);
      tempX[index] = runs[i];
      tempY[index] = rms[i];
    }
    
    //Making the graph
    
    TGraph* gr = new TGraph(389, tempX, tempY);
    
    TString temp;
    
    int channel = (int) graph - floor(graph/9);
    
    if((graph+1) % 9 != 0) temp.Form("Mean RMS of Channel %d of All Runs", channel);
    else temp.Form("Mean RMS of Trigger Channel %d of All Runs", (graph+1)/9);
    
    TCanvas* c  = new TCanvas("c", "c", 600, 600);
    
    c->cd();
    
    gr->SetTitle(temp.Data());
    gr->Draw("AP");
    
    temp.Form("./All Run Comparison/%d.root", graph);
    gr->SaveAs(temp.Data());
    
    temp.Form("./All Run Comparison/%d.png", graph);
    
    c->SaveAs(temp.Data());
  }
  
  return 1;
}